### ISSUE TITLE
Прием или отклонение нового заказа

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/android-diner-delivery#14]
Когда курьер видит новый заказ в приложении, он хочет принять или отклонить его, чтобы выбирать только выгодные для себя заказы.

> Описание истории, схемы, картинки и т.д. 

## Критерии готовности 

- [x] Курьеру удобно принять или отклонить заказ, потому что нужно понижать порог вхождения

## Связанное

Понадобится: 
- Retrofit: #11 
- Material Components: #13 
- RxJava: #7 
- Spring: #12 

> Всяческие подробности, ссылки, документация и т.д.

**Comment by Morgan-dev311** [comment]
Удобно, красиво, работает
