### ISSUE TITLE
Отображение физических параметров заказа 

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/android-diner-delivery#15]
Когда к курьеру приходит новый заказ, он хочет видеть специфику и массу содержимого, чтобы брать только _подходящие_ заказы.

Можно раскрыть смысл _подходящих_ заказов: 
- например, если у нас девочка-курьер, она может не потянуть тяжелый заказ, 
- если внутри напитки, то нести его нужно с тройной осторожностью, а курьер на велике, 
- или если внутри что-то, что имеет смысл есть только горячим, а курьер не на транспорте и заказ остынет.

В целом, сервер сам в перспективе должен определять, кому какой заказ предлагать, например горячие заказы только курьерам на транспорте, но в начале пусть сами курьеры решают.

## Критерии готовности 

- [x] Курьер сразу при приеме нового заказа видит специфику содержимого

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by Morgan-dev311** [comment]
Отображаются особенности содержимого и общий вес
