### ISSUE TITLE
🎨 Наброски UI для первых историй

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/android-diner-delivery#17]
![image](https://user-images.githubusercontent.com/11541555/99185428-4652a900-2763-11eb-8293-bf55ee47ce17.png)

Слева вверху то, как это может выглядеть при свернутом приложении:
- всплывает уведомление,
- в уведомлении заголовок: "Новый заказ!",
- В подробностях уведомления краткие параметры: "Срочно, напитки, 1300 г." и т.д., добавим по мере развития приложения,
- две кнопки "Принять" и "Отклонить",
- тап по уведомлению открывает приложение с подробностями заказа.

Справа снизу как может выглядеть экран с подробностями заказа:
- можно вывести UUID заказа,
- содержимое заказа с параметрами в виде списка/таблички, 
- две кнопки "Принять" и "Отклонить",
- может быть таймер на прием заказа, наверное.

Многое пока непонятно без описанной бизнес-логики.

## Связанное

Нужно для #14 #15 

> Всяческие подробности, ссылки, документация и т.д.

**Comment by ViRGiL175** [comment]
Давайте это закроем? @Morgan-dev311 @EsQLap 

Это было нужно только для первых двух историй, дальше я буду работать в Фигме, а не на листочке.

**Comment by EsQLap** [comment]
Можно

**Comment by Morgan-dev311** [comment]
+
